name: Rebase pull requests when main change

on:
  pull_request:
    types: [labeled]
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    name: 'Rebase branch on main'

    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.TOKEN_REPO_WRITE }}

    - name: 'Rebase one pull request based on main with label'
      uses: fp51/actions/rebase-pull-requests@v1
      with:
        # we use another token here
        # because an action in a workflow run can't trigger a new workflow run
        # with the GITHUB_TOKEN
        # @see https://help.github.com/en/articles/events-that-trigger-workflows#event-restrictions
        token: ${{ secrets.TOKEN_REPO_WRITE }}
        label: 'Action: keep-rebased-then-merge'
        gitUserName: ${{ secrets.BOT_NAME }}
        gitUserEmail: ${{ secrets.BOT_EMAIL }}

